Added files via upload
I kept running into various error messages when trying to push my my-favorite-things via git/the command line. I would seem to solve one problem, and then another error message would arise. My latest error is listed below (I tried running 'git pull' as it suggests to no avail). Long story short, i ended up manually uploading these files, but would still like to figure out how to push via terminal today!

SamsMB:my-favorite-things sambrooks$ git push origin master
To git@github.com:sbrks/command-line-lab.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:sbrks/command-line-lab.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.